


<h3>Les meilleurs ventes</h3>


<!-- <div class="slider">
	
		<div id="owl-example" class="owl-carousel">
			  <div><img src="./public/img/slider/slider1.jpg" alt=""></div>
			  <div><img src="./public/img/slider/slider2.jpg" alt=""></div>
			  <div> <img src="./public/img/slider/slider3.jpg" alt=""></div>
		</div>
</div>
 -->
<div class="wrapper-slider">
				<div class="slide">
					<div class="large-8 columns">
						<div id="header-slider">
							<img src="./public/img/slider/slider1.jpg" alt="">
							<img src="./public/img/slider/slider2.jpg" alt="">
							<img src="./public/img/slider/slider3.jpg" alt="">
						</div>
					</div>
					<div class="large-4 columns fnoir">
					
					<img src="./public/img/fennec_noir.png" alt="">
					<h4>Lorem ipsum dolor sit amet,</h4>


						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum earum ab nam quos nesciunt eligendi, sapiente nihil, consectetur facere molestiae nostrum culpa possimus tempore similique, amet veritatis suscipit. Doloremque, sequi.</p>
					</div>
				</div>
		</div>


<h3>categorie</h3>
<div class="row categorie">
	<div class="large-3 columns">
		<div class="bleu">
			<img src="./public/img/ptitfennec.png" alt="">
			<h4>fennec bleu</h4>

			<a href=""><img src="./public/img/fleche.png" alt=""></a>

		</div>
	</div>
	<div class="large-3 columns">
		<div class="orange">
			<img src="./public/img/ptitfennec.png" alt="">
			<h4>fennec orange</h4>
			<a href=""><img src="./public/img/fleche.png" alt=""></a>

		</div>
	</div>
	<div class="large-3 columns">
		<div class="vert">
			<img src="./public/img/ptitfennec.png" alt="">
			<h4>fennec vert</h4>
			<a href=""><img src="./public/img/fleche.png" alt=""></a>

		</div>
	</div>
	<div class="large-3 columns">
		<div class="gris">
			<img src="./public/img/ptitfennec.png" alt="">
			<h4>fennec gris</h4>
			<a href=""><img src="./public/img/fleche.png" alt=""></a>
		</div>
	</div>
</div>
<?php
require('apps/content/categories.php');
?>