	<h1><?=$item->getName()?></h1>
	<p><?=$item->getDescription()?></p>

	<form method="post" action="index.php?page=cart&id=<?=$item->getId()?>&action=add_item">
		<fieldset>
			<legend>La main au panier</legend>
			<input type="number" max="999" name="quantity" id="quantity" value="1" />
		<!-- ____ Attention vomi ____ -->
			<style>input[type="number"]{width:70px;}</style>
			<button type="submit">Ajouter</button>
		</fieldset>
	</form>

<?php
	require('apps/content/comments.php');
?>