	<h1><?=$item->getName()?></h1>
	<p><?=$item->getDescription()?></p>
	<p>Seulement <?=$item->getPrice()?> € le specimen !</p>

	<form method="post" action="index.php?page=cart&id=<?=$item->getId()?>&action=add_item">
		<fieldset>
			<legend><strong><?=$item->getStock()?></strong> en stock, <strong><?=$quantity?></strong> dans le panier</legend>
			<input type="number" min="-<?=$minValue?>" max="<?=$maxValue?>" name="quantity" id="quantity" value="<?=$defaultValue?>" />
		<!-- ____ Attention scandale ____ -->
			<style>input[type="number"]{width:70px;}</style>
		<!-- ________________ -->
			<button type="submit">Ajouter</button>
		</fieldset>
	</form>

<?php require('apps/content/comments.php'); ?>