<form method="POST" action="index.php?page=payment&action=checkCc">
	<fieldset>
		<legend>Carte bancaire</legend>
		<select name="cardName">
			<option value="American Express">American Express</option>
			<option value="Diners Club Carte Blanche">Diners Club Carte Blanche</option>
			<option value="Diners Club">Diners Club</option>
			<option value="Discover">Discover</option>
			<option value="Diners Club Enroute">Diners Club Enroute</option>
			<option value="JCB">JCB</option>
			<option value="Maestro">Maestro</option>
			<option value="MasterCard">MasterCard</option>
			<option value="Solo">Solo</option>
			<option value="Switch">Switch</option>
			<option value="VISA">VISA</option>
			<option value="VISA Electron">VISA Electron</option>
			<option value="LaserCard">LaserCard</option>
		</select>
		<input type="text" id="cardNumber" name="cardNumber" placeholder="Numéro de carte" />
		<button type="submit">Valider</button>