<!-- <div>
	<h3><?php echo ($subCategory->getName()); ?></h3>


</div> -->

<form method="post" action="">
	<h3>creation sous category</h3>
	<div class="row">
		<div class="small-12 columns">
			<label>nom :
				<input type="text" id="name" name="name" value="<?=(isset($subcategory)) ? htmlentities($name_subcategory) : ""?>">
			</label>
		</div>
		<div class="small-12 columns">
			<label>description :
				<input type="text" id="description" name="description" value="<?= (isset($subcategory)) ? htmlentities($subcategory) : "" ?>">
			</label>		
		</div>
		<div class="small-12 columns">
			<label>image:
				<input type="text" id="image" name="image" value="<?=(isset($subcategory)) ? htmlentities($image) : ""?>" />
			</label>
		</div>
		<div class="small-12 columns">	
			<button class="button success" type="submit">Valider</button>
		</div>
	</div>
</form>
