<div class="large-4 columns">
<h1>FennecPlusUltra</h1>
</div>
<div class="large-4 columns">
	<ul class="menu">
      <li><input type="search" placeholder="Search"></li>
      <li><button type="button" class="button">Search</button></li>
    </ul>
</div>

<div class="large-4 columns">
	<?php require('apps/cart_mini.php'); ?>
</div>

<div class="small-12 columns">
	<?php require('apps/nav.php'); ?>
</div>

