<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="./public/css/app.css">
	<link rel="stylesheet" href="./public/css/fondation.min.css">
	<script type="text/javascript" src="./public/js/fondation.min.js"></script>
	
	<script type="text/javascript" src="./public/js/app.js"></script>

	
	
	<title>FennecPlusUltra</title>
</head>
<body>
	<div class="container">
		<?php
		require('apps/header.php');
		require('apps/content.php');
		require('apps/footer.php');

		?>
		
	</div>
</body>
</html>